### ISSUE TITLE
GithubRepo and PagerDutyServiceId to MESSAGE-SPEC

### ISSUE THREAD

**Issue by k-mahoney** [mapbox/dispatch#111]
Currently `GithubRepo` and `PagerDutyServiceId` are defined in the CloudFormation template here: [incoming/function.template.js](https://github.com/mapbox/dispatch/blob/master/incoming/function.template.js). In order for a `dispatch` stack to be used by any team, these parameters should be specified at the [message spec level](https://github.com/mapbox/dispatch/blob/master/MESSAGE-SPEC.md). That way,  `dispatch` can handle any alert from any team meant for any PagerDuty Service or GitHub repository.

Additional thought here, any `dispatch` Slack failures are posted to the default Slack channel -
 specified by the CloudFormation template as `SlackChannel`. I think this should remain a stack parameter rather than being set at the message specification level for now, in that the team who has deployed `dispatch` it can be responsible for errors in how it runs. Totally open for discussion though.

/cc @zmully @matiskay

**Comment by matiskay** [comment]
Right now,`GithubRepo` can be defined in the message level.  This is documented in the [message specification](https://github.com/mapbox/dispatch/blob/master/MESSAGE-SPEC.md).
https://github.com/mapbox/dispatch/blob/4dbb354ff05f0d6370285655e538ccd5f3b05b11/incoming/function.js#L41

We can do the same for `PagerDutyServiceId`, right now the variable comes from the ENV variables.
https://github.com/mapbox/dispatch/blob/4dbb354ff05f0d6370285655e538ccd5f3b05b11/incoming/function.js#L17

**Comment by k-mahoney** [comment]
Oh woah, I totally forgot we'd already added that. I even wrote it too. :man_facepalming: 
Alright awesome! That just leaves the `PagerDutyServiceId` - thanks @matiskay.
